DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN CITY VARCHAR(50) NOT NULL;

ALTER TABLE CUSTOMERS
ADD COLUMN COUNTRY VARCHAR(50) NOT NULL;

ALTER TABLE EMPLOYEES
MODIFY COLUMN GENDER VARCHAR(10) NOT NULL;