CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID BIGINT AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE PRODUCTS
(
	PRODUCT_ID BIGINT AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE ORDERS
(
	ORDER_ID BIGINT AUTO_INCREMENT,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_DT DATETIME NOT NULL,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ITEMS
(
	ITEM_ID BIGINT AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRIMARY KEY(ITEM_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE EMPLOYEES
(
	EMPLOYEE_ID BIGINT AUTO_INCREMENT,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    ADDRESS TEXT NOT NULL,
    AGE INT(3) NOT NULL,
    GENDER VARCHAR(5) NOT NULL,
    PRIMARY KEY(EMPLOYEE_ID)
);